apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vrqu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vrqu
    app.kubernetes.io/part-of: ci10t-777-0015-app
  name: devfile-sample-vrqu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vrqu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vrqu
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0015-tenant/ci10t-777-0015-app/devfile-sample-vrqu@sha256:d82757d4a13e0cd72d1d96975517c71ac2639c3928deef8df773e6eafee393cb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
